config/routes.rb
Rails.application.routes.draw do
  root 'nappis#index'
  resources :nappis
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/nappi.rb
class Nappi < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/nappis_controller.rb
class NappisController < ApplicationController
  before_action :set_nappi, only: [:show, :edit, :update, :destroy]

  # GET /nappis
  # GET /nappis.json
  def index
    @nappis = Nappi.all
  end

  # GET /nappis/1
  # GET /nappis/1.json
  def show
  end

  # GET /nappis/new
  def new
    @nappi = Nappi.new
  end

  # GET /nappis/1/edit
  def edit
  end

  # POST /nappis
  # POST /nappis.json
  def create
    @nappi = Nappi.new(nappi_params)

    respond_to do |format|
      if @nappi.save
        format.html { redirect_to @nappi, notice: 'Nappi was successfully created.' }
        format.json { render :show, status: :created, location: @nappi }
      else
        format.html { render :new }
        format.json { render json: @nappi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nappis/1
  # PATCH/PUT /nappis/1.json
  def update
    respond_to do |format|
      if @nappi.update(nappi_params)
        format.html { redirect_to @nappi, notice: 'Nappi was successfully updated.' }
        format.json { render :show, status: :ok, location: @nappi }
      else
        format.html { render :edit }
        format.json { render json: @nappi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nappis/1
  # DELETE /nappis/1.json
  def destroy
    @nappi.destroy
    respond_to do |format|
      format.html { redirect_to nappis_url, notice: 'Nappi was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nappi
      @nappi = Nappi.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nappi_params
      params.require(:nappi).permit(:year, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nappis_helper.rb
module NappisHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaiseiDays</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/nappis/_form.html.erb
<%= form_with(model: nappi, local: true) do |form| %>
  <% if nappi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(nappi.errors.count, "error") %> prohibited this nappi from being saved:</h2>

      <ul>
      <% nappi.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :year %>
    <%= form.text_field :year %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.text_field :age %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/nappis/edit.html.erb
<h1>Editing Nappi</h1>

<%= render 'form', nappi: @nappi %>

<%= link_to 'Show', @nappi %> |
<%= link_to 'Back', nappis_path %>

app/views/nappis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Nappis</h1>

<table>
  <thead>
    <tr>
      <th>Year</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nappis.each do |nappi| %>
      <tr>
        <td><%= nappi.year %></td>
        <td><%= nappi.age %></td>
        <td><%= link_to 'Show', nappi %></td>
        <td><%= link_to 'Edit', edit_nappi_path(nappi) %></td>
        <td><%= link_to 'Destroy', nappi, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Nappi', new_nappi_path %>

app/views/nappis/new.html.erb
<h1>New Nappi</h1>

<%= render 'form', nappi: @nappi %>

<%= link_to 'Back', nappis_path %>

app/views/nappis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Year:</strong>
  <%= @nappi.year %>
</p>

<p>
  <strong>Age:</strong>
  <%= @nappi.age %>
</p>

<%= link_to 'Edit', edit_nappi_path(@nappi) %> |
<%= link_to 'Back', nappis_path %>